# updated 011725
# Anne-Cecile Lesage
# UTMB
# write montage in RAVE format using electrodes localization

library(tcltk)

# open electrode localization file generated by YAEL
dfelec<-read.csv(tk_choose.files(caption="Choose electrodes*.csv file"))
# open channel file describing electrode montage
dfchannel<-read.csv(tk_choose.files(caption="Choose *channels.csv file"))

namechannel<-dfchannel$name
#rename channels on the left starting by L and on the right by R (Rave standard) of electrodes file
for (i in 1:length(namechannel)){
#  i=134
  left=0
  namei<-namechannel[i]
  elecname<-gsub("[^a-zA-Z]", "", namei)
  contactnb<-gsub("[^0-9]", "", namei)
  j<-nchar(elecname)+1
  if(substr(namei,j,j)=="'"){
    left=1
    newname<-paste('L',elecname,contactnb,sep="")
    namechannel[i]<-newname
  }else{
    newname<-paste('R',namei,sep="")
    namechannel[i]<-newname
  }
}

dfchannel$name<-namechannel

for (i in 1:length(namechannel)){
#i=6
  namei<-namechannel[i]
  j<-which(dfelec$Label==namei)
  x<-dfelec$Coord_x[j]
  y<-dfelec$Coord_y[j]
  z<-dfelec$Coord_z[j]
  dfchannel$x[i]<-x
  dfchannel$y[i]<-y
  dfchannel$z[i]<-z

}

write.csv(dfchannel,"sub-k013-ses-presurgery_task-ictal_acq-seeg_channels.csv")
